### PR TITLE
Updated Colors and hover effect of the form

### PR DESCRIPTION
**Pull request by SaranshBaniyal**

### CODE REVIEW

**Comment by SaranshBaniyal** [comment]
I have created a PR please take a look. 
PS:- Please also add the hacktoberfest label

**Comment by Soumyajit2825** [comment]
SOLVE THE MERGE CONFLICT ISSUES AND THEN MAKE THE PR ALSO GIVE A SCREEN SHOT OF YOUR WORK

**Comment by Soumyajit2825** [comment]
@SaranshBaniyal can u give a screen shot of your work

**Comment by SaranshBaniyal** [comment]
Screenshot 2022-10-13 195342

**Comment by SaranshBaniyal** [comment]
image

**Comment by Soumyajit2825** [comment]
already done

**Comment by SaranshBaniyal** [comment]
@Soumyajit2825 thanks a lot

**Comment by Soumyajit2825** [comment]
star our repo for getting connected with us in further

**Comment by SaranshBaniyal** [comment]
@Soumyajit2825 sure thing

**Pull request merged**
